/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoesauction.Frame;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import shoesauction.Connection.DBConnection;
import shoesauction.Controller.MainController;
import shoesauction.Helper.Helper;
import shoesauction.Model.MainModel;
import shoesauction.Query.MainQuery;

/**
 *
 * @author Dhimas N A
 */
public class AdminTransaction extends javax.swing.JFrame {

    String sql;
    ResultSet rs; 
    Statement st;
    Connection con;
    String id;
    MainQuery query = new MainQuery();
    MainController controller = new MainController();
    Helper helper = new Helper();
    MainModel model = new MainModel();
    
    /**
     * Creates new form AdminTransaction
     */
    public AdminTransaction() {
        initComponents();
        
        DBConnection koneksi = new DBConnection();
        koneksi.open();
        con = koneksi.con;
        st = koneksi.stm;
        
        tf_idTransaction.setEnabled(false);
        tf_idbid.setEnabled(false);
        cb_product();
        cb_username();
        getAllDataBid();
        getAllDataTr();
        createIDtransaction();
        
        tf_total.setText("1");
        tf_total.setEnabled(false);
    }

    private void createIDtransaction(){
       try {
            sql = this.query.createIDtransaction;
            st = con.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                String id_transaksi = rs.getString("id_transaksi").substring(2);
                String kode = "" + (Integer.parseInt(id_transaksi) + 1);
                String nol = "";

                if(kode.length()==1)
                {nol = "000";}
                else if(kode.length()==2)
                {nol = "00";}
                else if(kode.length()==3)
                {nol = "0";}
                else if(kode.length()==4)
                {nol = "";}

               tf_idTransaction.setText("TR" + nol + kode);
            } 
            else {
               tf_idTransaction.setText("TR0001");
            }
           }
       catch(Exception ex){
           System.out.println(ex.getMessage());
           }
     }
    
    public void cb_product(){
        try {
        
            sql = this.query.cb_product;
            st = con.createStatement();
            rs = st.executeQuery(sql);                                
        
            while(rs.next()){
            Object[] ob = new Object[3];
            ob[0] = rs.getString(1);
            
            cb_product.addItem(ob[0]);        
        }
        rs.close(); st.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void cb_username(){
        try {
        
            sql = this.query.getUsername;
            st = con.createStatement();
            rs = st.executeQuery(sql);                                
        
            while(rs.next()){
            Object[] ob = new Object[3];
            ob[0] = rs.getString(1);
            
            cb_username.addItem(ob[0]);        
        }
        rs.close(); st.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void getAllDataBid(){
        this.rs = controller.getBid();
        loadTableBid(this.rs);
    }
    
    public void getAllDataTr(){
        this.rs = controller.getTransaction();
        loadTableTr(rs);
    }
    
    public void loadTableBid(ResultSet rs){
        tb_bid.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    public void loadTableTr(ResultSet rs){
        tb_transaction.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    public void clear(){
        tf_idbid.setText("");
        cb_product.setSelectedItem(0);
        cb_username.setSelectedItem(0);
        tf_endbid.setText("");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_bid = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_idTransaction = new javax.swing.JTextField();
        tf_idbid = new javax.swing.JTextField();
        tf_total = new javax.swing.JTextField();
        tf_endbid = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        cb_product = new javax.swing.JComboBox();
        cb_username = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_transaction = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_bid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_bid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_bidMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_bid);

        jLabel1.setText("ID Transaction");

        jLabel2.setText("ID Bid");

        jLabel3.setText("ID Product");

        jLabel4.setText("Username");

        jLabel5.setText("Total");

        jLabel6.setText("End Bid");

        tf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_totalActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        cb_product.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Choose-" }));

        cb_username.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Choose-" }));

        tb_transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_transactionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_transaction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_endbid)
                                .addComponent(tf_total)
                                .addComponent(tf_idTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(tf_idbid))
                            .addComponent(btn_submit)
                            .addComponent(btn_update)
                            .addComponent(btn_delete)
                            .addComponent(cb_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_idTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_idbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cb_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_endbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_bidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_bidMouseClicked
        // TODO add your handling code here:
        try{
            String id_bid = helper.getValuesRows(tb_bid, 0);
            String id_product = helper.getValuesRows(tb_bid, 1);
            String end_bid = helper.getValuesRows(tb_bid, 2);
            String username = helper.getValuesRows(tb_bid, 3);
            
            tf_idbid.setText(id_bid);
            cb_product.setSelectedItem(id_product);
            cb_username.setSelectedItem(username);
            tf_endbid.setText(end_bid);
        }
        catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tb_bidMouseClicked

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        try {
            String id_transaction = tf_idTransaction.getText();
            String id_bid = tf_idbid.getText();
            String id_product = cb_product.getSelectedItem().toString();
            String total = tf_total.getText();
            String end_bid = tf_endbid.getText();
            String username = cb_username.getSelectedItem().toString();

            model.setId_transaction(id_transaction);
            model.setId_bid(id_bid);
            model.setId_product(id_product);
            model.setTotal(total);
            model.setTotal_bid(end_bid);
            model.setUsername(username);

            Boolean result = controller.createTransaction(model);
            if(result){
                JOptionPane.showMessageDialog(null, "berhasil menambahkan data!");
            }
            else {
                JOptionPane.showMessageDialog(null, "gagal menambahkan");
            }
            getAllDataTr();
            clear();
            }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try{
            Boolean result = controller.deleteTransaction(id);
            
            if(result){
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal Menghapus Data");
            }
            clear();
            getAllDataTr();
                    
        }
        catch (Exception ex){
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        try {
            String id_transaction = tf_idTransaction.getText();
            String id_bid = tf_idbid.getText();
            String id_product = cb_product.getSelectedItem().toString();
            String total = tf_total.getText();
            String end_bid = tf_endbid.getText();
            String username = cb_username.getSelectedItem().toString();

            model.setId_transaction(id_transaction);
            model.setId_bid(id_bid);
            model.setId_product(id_product);
            model.setTotal(total);
            model.setTotal_bid(end_bid);
            model.setUsername(username);

            Boolean result = controller.updateTransaction(id, model);
            if(result){
                JOptionPane.showMessageDialog(null, "berhasil menambahkan data!");
            }
            else {
                JOptionPane.showMessageDialog(null, "gagal menambahkan");
            }
            getAllDataTr();
            clear();
            }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tb_transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_transactionMouseClicked
        // TODO add your handling code here:
        try{
            String id_transacation = helper.getValuesRows(tb_transaction, 0);
            String id_bid = helper.getValuesRows(tb_transaction, 1);
            String id_product = helper.getValuesRows(tb_transaction, 2);
            String username = helper.getValuesRows(tb_transaction, 3);
            String total = helper.getValuesRows(tb_transaction, 4);
            String end_bid = helper.getValuesRows(tb_transaction, 5);
            
            tf_idTransaction.setText(id_transacation);
            tf_idbid.setText(id_bid);
            cb_product.setSelectedItem(id_product);
            cb_username.setSelectedItem(username);
            tf_total.setText(total);
            tf_endbid.setText(end_bid);
        }
        catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tb_transactionMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here
        DashboardAdmin da = new DashboardAdmin();
        da.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void tf_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox cb_product;
    private javax.swing.JComboBox cb_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_bid;
    private javax.swing.JTable tb_transaction;
    private javax.swing.JTextField tf_endbid;
    private javax.swing.JTextField tf_idTransaction;
    private javax.swing.JTextField tf_idbid;
    private javax.swing.JTextField tf_total;
    // End of variables declaration//GEN-END:variables
}
